# Generated by Django 5.2.7 on 2025-10-28 02:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)], verbose_name='Año')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Maintenance', 'Maintenance'), ('Out of service', 'Out of service')], default='Active', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['plate'], name='vehicles_ve_plate_f1ecfa_idx')],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(max_length=50, verbose_name='Tipo de Mantenimiento')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='vehicles.vehicle', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='vehicles_ma_date_aacf8a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=50, verbose_name='Tipo de Documento')),
                ('issue_date', models.DateField(verbose_name='Fecha de Emisión')),
                ('expiry_date', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-expiry_date'],
                'indexes': [models.Index(fields=['expiry_date'], name='vehicles_do_expiry__3b80a2_idx')],
            },
        ),
    ]
