# Generated by Django 5.2.7 on 2025-10-28 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehiclechecklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('validity_months', models.IntegerField(blank=True, null=True, verbose_name='Vigencia (meses)')),
                ('is_required', models.BooleanField(default=True, verbose_name='Obligatorio')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número de Documento'),
        ),
        migrations.AddField(
            model_name='document',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicles.documenttype', verbose_name='Tipo de Documento'),
        ),
    ]
