# Generated by Django 5.2.7 on 2025-10-28 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_documenttype_document_document_number_document_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('license_number', models.CharField(max_length=50, verbose_name='Número de Licencia')),
                ('license_expiry', models.DateField(verbose_name='Vencimiento de Licencia')),
                ('hire_date', models.DateField(verbose_name='Fecha de Contratación')),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Vacaciones', 'Vacaciones')], default='Activo', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chofer',
                'verbose_name_plural': 'Choferes',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('INE', 'INE / Identificación Oficial'), ('Licencia', 'Licencia de Conducir'), ('Antecedentes', 'Carta de No Antecedentes Penales'), ('Solicitud', 'Solicitud de Empleo'), ('Comprobante', 'Comprobante de Domicilio'), ('CURP', 'CURP'), ('RFC', 'RFC'), ('NSS', 'Número de Seguro Social'), ('Contrato', 'Contrato Laboral'), ('Otro', 'Otro Documento')], max_length=50, verbose_name='Tipo de Documento')),
                ('document_file', models.ImageField(upload_to='driver_documents/', verbose_name='Archivo')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.driver', verbose_name='Chofer')),
            ],
            options={
                'verbose_name': 'Documento de Chofer',
                'verbose_name_plural': 'Documentos de Choferes',
                'ordering': ['-upload_date'],
            },
        ),
    ]
