# Generated by Django 5.2.7 on 2025-10-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_driver_driverdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='position',
            field=models.CharField(default='Chofer', max_length=100, verbose_name='Puesto'),
        ),
    ]
