# Generated by Django 5.2.7 on 2025-10-28 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_driver_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['full_name'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Lista de Empleados'},
        ),
        migrations.AlterModelOptions(
            name='driverdocument',
            options={'ordering': ['-upload_date'], 'verbose_name': 'Documento de Empleado', 'verbose_name_plural': 'Documentos de Empleados'},
        ),
        migrations.AlterField(
            model_name='driverdocument',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.driver', verbose_name='Empleado'),
        ),
    ]
