# Generated by Django 5.2.7 on 2025-10-28 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_change_driver_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.documenttype', verbose_name='Tipo de Documento'),
        ),
    ]
