# Generated by Django 5.2.7 on 2025-10-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_change_document_type_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_file',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_documents/', verbose_name='Archivo'),
        ),
    ]
