# Generated by Django 5.2.7 on 2025-10-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_add_workshop_and_maintenance_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='maintenance_invoices/', verbose_name='Factura'),
        ),
    ]
