# Generated by Django 5.2.7 on 2025-10-28 05:14

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_change_invoice_to_filefield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mantenimiento', 'verbose_name_plural': 'Mantenimientos'},
        ),
        migrations.RemoveIndex(
            model_name='maintenance',
            name='vehicles_ma_date_aacf8a_idx',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='approval_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Aprobación'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='approval_notes',
            field=models.TextField(blank=True, verbose_name='Notas de Aprobación'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='approved_by',
            field=models.CharField(blank=True, max_length=200, verbose_name='Aprobado por'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='detected_by',
            field=models.CharField(default='Sistema', max_length=200, verbose_name='Detectado por'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='detection_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Detección'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenance',
            name='problem_description',
            field=models.TextField(default='', verbose_name='Descripción del Problema'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='quote_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Cotización'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='quote_file',
            field=models.FileField(blank=True, null=True, upload_to='maintenance_quotes/', verbose_name='Archivo de Cotización'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='status',
            field=models.CharField(choices=[('Detectado', 'Detectado'), ('Cotizado', 'Cotizado'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Completado', 'Completado')], default='Detectado', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Real'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Realización'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Cotizado'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['status'], name='vehicles_ma_status_4dcc15_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['detection_date'], name='vehicles_ma_detecti_53870b_idx'),
        ),
    ]
