# Generated by Django 5.2.7 on 2025-10-30 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0013_alter_maintenance_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número')),
                ('iccid', models.CharField(max_length=30, unique=True, verbose_name='ICCID')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Suspendido', 'Suspendido')], default='Activo', max_length=20, verbose_name='Estado')),
                ('operador', models.CharField(choices=[('Telcel', 'Telcel'), ('Movistar', 'Movistar'), ('AT&T', 'AT&T'), ('Otro', 'Otro')], max_length=50, verbose_name='Operador')),
                ('fecha_activacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Activación')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'SIM',
                'verbose_name_plural': 'SIMs',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
