# Generated by Django 5.2.7 on 2025-10-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0014_sim'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='station',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estación'),
        ),
    ]
