# Generated by Django 5.2.7 on 2025-10-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0015_vehicle_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='station',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estación'),
        ),
        migrations.AddField(
            model_name='vehiclechecklist',
            name='station',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estación'),
        ),
    ]
